//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public string Comment1 { get; set; }
        public Nullable<bool> Seem { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<int> Product { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
