//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class devvn_xaphuongthitran
    {
        public string xaid { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string maqh { get; set; }
    
        public virtual devvn_quanhuyen devvn_quanhuyen { get; set; }
    }
}
