//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Category { get; set; }
        public string Detail { get; set; }
        public string Source { get; set; }
        public string SourceDetail { get; set; }
        public Nullable<System.DateTime> ShelfLife { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Image { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<bool> Active { get; set; }
        public int CountOrder { get; set; }
    }
}
