//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopAuto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopInformation
    {
        public int ID { get; set; }
        public string NameShop { get; set; }
        public string IconShop { get; set; }
        public string AddressShop { get; set; }
        public string About { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string BankAcc { get; set; }
        public string Email { get; set; }
        public string PassWordEmail { get; set; }
        public string FaceBook { get; set; }
        public string Google { get; set; }
        public string Zalo { get; set; }
        public string URLMap { get; set; }
        public string Keywords { get; set; }
    }
}
